[build]
  # Build only the frontend for Netlify deployment
  command = "vite build"
  publish = "dist/public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# API function redirects
[[redirects]]
  from = "/api/companions/:id"
  to = "/.netlify/functions/companion"
  status = 200

[[redirects]]
  from = "/api/companions"
  to = "/.netlify/functions/companions"
  status = 200

[[redirects]]
  from = "/api/bookings"
  to = "/.netlify/functions/bookings"
  status = 200

[[redirects]]
  from = "/api/reviews"
  to = "/.netlify/functions/reviews"
  status = 200

[[redirects]]
  from = "/api/auth/user"
  to = "/.netlify/functions/auth-user"
  status = 200

[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200

[[redirects]]
  from = "/api/newsletter"
  to = "/.netlify/functions/newsletter"
  status = 200

[[redirects]]
  from = "/api/favorites"
  to = "/.netlify/functions/favorites"
  status = 200

[[redirects]]
  from = "/api/favorites/:id"
  to = "/.netlify/functions/favorites"
  status = 200

[[redirects]]
  from = "/api/companion-availability"
  to = "/.netlify/functions/companion-availability"
  status = 200

# Catch-all redirect for SPA routing (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200